# Generated by Django 5.0.2 on 2024-03-06 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=15)),
                ('birthdate', models.DateField()),
                ('emial', models.EmailField(max_length=254)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=12, null=True)),
                ('state', models.CharField(blank=True, max_length=14, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=12, null=True)),
                ('emergency_contact_mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=8, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('statusReason', models.CharField(blank=True, max_length=80)),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('procedure_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=25)),
                ('clinic_address', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('report', models.FileField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EMR_App.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
