# Generated by Django 5.0.2 on 2024-03-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contant_mobile_number',
            new_name='emergency_contact_mobile_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contant_name',
            new_name='emergency_contact_name',
        ),
    ]
