# Generated by Django 5.0.2 on 2024-03-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_App', '0002_rename_emial_patient_email_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='type',
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
