# Generated by Django 5.0.2 on 2024-03-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_App', '0002_rename_emial_patient_email_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokenexpired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField()),
            ],
        ),
    ]
