# Generated by Django 5.0.2 on 2024-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_App', '0003_remove_procedure_type_procedure_procedure_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(max_length=100),
        ),
    ]
