# Generated by Django 5.0.2 on 2024-04-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_App', '0004_alter_procedure_procedure_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patient_data',
        ),
    ]
