# Generated by Django 5.0.2 on 2024-04-22 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMR_App', '0005_rename_patient_patient_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedure',
            new_name='Procedure_data',
        ),
    ]
